name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Create virtual environment
      run: python -m venv venv
      
    - name: Install dependencies
      shell: bash
      run: |
        source venv/bin/activate
        pip install uv
        uv pip install -r requirements.txt
    
    - name: Run Django checks
      shell: bash
      run: |
        source venv/bin/activate
        python manage.py check
        python manage.py migrate
        python manage.py test
